DROP TABLE IF EXISTS "user","token","connection","role","image","file";
CREATE TABLE IF NOT EXISTS "role"(
	"id" SERIAL NOT NULL PRIMARY KEY,
	"title" CHARACTER VARYING(500) NOT NULL
);
CREATE TABLE IF NOT EXISTS "department"(
	"id" SERIAL NOT NULL PRIMARY KEY,
	"title" CHARACTER VARYING(500) NOT NULL
);
CREATE TABLE IF NOT EXISTS "user"(
  "id" BIGSERIAL NOT NULL PRIMARY KEY,
  "email" CHARACTER VARYING(255) NOT NULL,
  "password" CHARACTER VARYING(60) NOT NULL,
  "is_activated" BOOLEAN NOT NULL DEFAULT FALSE,
  "activation_link" CHARACTER VARYING(255) NOT NULL,
  "created_at" TIMESTAMP(3) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP(3)::TIMESTAMP,
  "role" INT NOT NULL REFERENCES "role"("id") DEFAULT 1,
  "department" INT REFERENCES "department"("id"),
  "online_at" TIMESTAMP(3) WITHOUT TIME ZONE
);
CREATE TABLE IF NOT EXISTS "token"(
  "id" BIGSERIAL NOT NULL PRIMARY KEY,
  "id_user" BIGINT NOT NULL REFERENCES "user"("id") ON DELETE CASCADE,
  "device_id" TEXT NOT NULL,
  "refresh_token" TEXT NOT NULL,
  "access_token" TEXT NOT NULL,
  "expires" TIMESTAMP(3) WITHOUT TIME ZONE NOT NULL,
  "location" CHARACTER VARYING (255)
);
CREATE TABLE IF NOT EXISTS "connection"(
  "id" BIGSERIAL NOT NULL PRIMARY KEY,
  "id_token" BIGINT NOT NULL REFERENCES "token"("id"),
  "peer" CHARACTER VARYING(36) NOT NULL
);
CREATE TABLE IF NOT EXISTS "image"(
  "id" BIGSERIAL NOT NULL PRIMARY KEY,
  "title" CHARACTER VARYING(500) NOT NULL,
  "x64" CHARACTER VARYING(2000) NOT NULL,
  "x512" CHARACTER VARYING(2000) NOT NULL,
  "x1080" CHARACTER VARYING(2000) NOT NULL,
  "original" CHARACTER VARYING(2000) NOT NULL,
  "created_at" TIMESTAMP(3) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP(3)::TIMESTAMP
);
CREATE TABLE IF NOT EXISTS "file"(
  "id" BIGSERIAL NOT NULL PRIMARY KEY,
  "title" CHARACTER VARYING(500) NOT NULL,
  "path" CHARACTER VARYING(2000) NOT NULL,
  "created_at" TIMESTAMP(3) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP(3)::TIMESTAMP
);
CREATE TABLE IF NOT EXISTS "project"(
  "id" BIGSERIAL NOT NULL PRIMARY KEY,
  "title" CHARACTER VARYING(500) NOT NULL,
  "created_at" TIMESTAMP(3) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP(3)::TIMESTAMP
);
CREATE TABLE IF NOT EXISTS "userProject"(
  "id" BIGSERIAL NOT NULL PRIMARY KEY,
  "id_user" BIGINT NOT NULL REFERENCES "user"("id"),
  "id_project" BIGINT NOT NULL REFERENCES "project"("id"),
  "created_at" TIMESTAMP(3) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP(3)::TIMESTAMP
);
CREATE TABLE IF NOT EXISTS "userProjectSpentHours"(
  "id" BIGSERIAL NOT NULL PRIMARY KEY,
  "id_userProject" BIGINT NOT NULL REFERENCES "userProject"("id") ON DELETE CASCADE,
  "spent_hours" INT NOT NULL,
  "created_at" TIMESTAMP(3) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP(3)::TIMESTAMP
);
INSERT INTO "role" ("title") VALUES ('user');
SELECT * FROM "token";
SELECT * FROM "role";
SELECT * FROM "user";
